query($start: Int, $limit: Int, $sort: String, $where:JSON) {
  customers(start:$start, limit:$limit, sort:$sort, where:$where){
    id
    record_no
    fin_year
    date
    customer_no
    customer_name
    description
    owed
    owned
  }
}
