query($start: Int, $limit: Int, $sort: String, $where:JSON) {
             sellers(start:$start, limit:$limit, sort:$sort, where:$where){
                id
                fin_year
                record_no
                date
                expire_date
                seller_no
                seller_name
                description
                product_no
                product
                payment
                first_unit
                quantity
                rate
              }
          }
